[script:splunk_query_tester_query_tester]
match = /splunk_query_tester/query_tester
script = query_tester.py
scripttype = persist
handler = query_tester.QueryTesterHandler
requireAuthentication = true
output_mode = json
passPayload = true
passHttpHeaders = true
passHttpCookies = true
python.version = python3
