[id]
name = query-tester-indexer
version = 0.1.0

[ui]
is_visible = 0
label = Query Tester (Indexer)

[launcher]
author = Splunk
description = Index configuration for Query Tester. Deploy to indexers via cluster master.
version = 0.1.0

[package]
check_for_updates = 0
id = QueryTesterIndexer

[install]
is_configured = 1
build = 1
